version: "3.9"

services:
  app:
    container_name: node-test
    build:
      context: .
      args:
      - WORKDIR=${WORKDIR}
      # - BUILDENV=${BUILDENV}
    ports:
      - "4000:4000"
    volumes:
      - "./docker-bind/logs:${WORKDIR}/logs"
    environment:
      - TZ = "Asia/Seoul"
      - BUILDENV=${BUILDENV}
    # env_file:
    #   - path: .docker.env
    #     required: true

    # entrypoint: ["/bin/bash"]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ${WORKDIR}/entrypoint.sh
    tty: true